### PR TITLE
Release v0.3

### PR DESCRIPTION
**Pull request by mkelley**
Reviewing all documentation and infrastructure items for v0.3 release.

This is a work in progress.

Items being reviewed:
* Timeline for main development (v1.0 now due in 2024).
* Funding acknowledgements.
* Development assignments.
* Installation instructions.
* Any mentions of versions, sbpy or otherwise.
* readthedocs environment
* CHANGES

### CODE REVIEW

**Comment by mkelley** [comment]
@jianyangli @migueldvb I think this PR is ready.  Please give the changes a look over and let me know if I've missed anything.

**Review by migueldvb — APPROVED** [review]
Everything looks good! Just the release date needs to be added in the 0.3.0 heading in CHANGES.rst. Thank you

**Review by jianyangli — APPROVED** [review]
Just a few small fixes for typos and about `sbpy.photometry` submodule description that I just pushed to the PR.  Otherwise everything looks good to me!  Thanks Mike.

**Comment by mkelley** [comment]
Thanks!  I'm about to go on vacation, so this may not be released until I'm back.

**Pull request merged**
