### PR TITLE
Photometry

### PR DESCRIPTION
**Pull request by jianyangli**
Implementation of IAU HG, HG1G2, and HG12 models, and initial implementation of some disk-functions

### CODE REVIEW

**Comment by mkelley** [comment]
Hi Jian-Yang,

When updating a branch to match master, it is preferable to use `git rebase` instead of `git merge`.  That will limit the commit history to just the changes for your branch.  I'm not sure if there is a way to fix this branch now.  Maybe @mommermi or @migueldvb has a recommendation?

**Comment by mommermi** [comment]
First of all, thanks for creating this pull request! I think it is not yet too late for a rebase on master. I think I've done this before. If you need help, let us know!

**Comment by jianyangli** [comment]
Hi @mkelley and @mommermi , I still need to explore rebase vs. merge.  So if someone could help me fix this branch `photometry`, or let me know how, I'll really appreciate it.  Also, as I'm currently on paternity leave and will not be able to work on this for another month at least, there is no rush.  Thanks.

**Comment by mommermi** [comment]
Sure, I will try to do the rebase later today and then review the code.

**Comment by mommermi** [comment]
@jianyangli, I did the rebase but there were some conflicts. Could you please resolve them? I had a look at them but I wasn't sure which version you wanted to keep in some places.

**Comment by jianyangli** [comment]
@mommermi I will look at it in a few weeks.  Thanks.

**Comment by mommermi** [comment]
Thanks, Jian-Yang, the rebase looks good to me. An easier way might be to close this pull request and open a new one from ``photometry_test_rebase``. I will then review and test the code and merge it as soon as possible. This will be a great addition for the EPSC workshop. Thanks!

**Comment by jianyangli** [comment]
Closed for rebase

**Pull request closed without merging**
