### PR TITLE
Photometry

### PR DESCRIPTION
**Pull request by jianyangli**
The PR is to support release v0.1.  The main updates on this PR are:

1. Implemented the revised HG12 model by Penttilä et al. (2016).
1. Add `.from_data()` class method
1. Add `.fit()` method as a wrapper to take `sbpy.data.Ephem` as input
1. Update the input/output to a few methods to allow `sbpy.data.Ephem`
1. Add support for units in data and models
1. Other miscellaneous update to support the above changes
1. Miscellaneous bugfix

This PR is also related to issue #112

### CODE REVIEW

**Comment by jianyangli** [comment]
@mommermi @mkelley I'm trying to rebase this branch to `master`, but it becomes extremely difficult now after the PR #103 was merged because it changed the same file 'photometry/core.py' and 'photometry/tests/test_core.py' a lot and caused numerous conflicts.  I tried to deconflict on my local repo but couldn't get it work after a long time.  On the other hand, merge with `master` is much easier to do and I quickly got it to work.  So could someone help me please if we really want to do rebase rather than merge here.  Thanks.

**Comment by migueldvb** [comment]
Rebasing helps to keep the project history linear. However it stops for every conflicting commit and it can be inconvenient. Astropy prefers rebasing PRs but I don't remember if we have a policy about this? Perhaps here, if you have merged master into your branch, you may rebase on master with:
```
git checkout master
git branch -b photometry_rebase
git merge --squash photometry
git commit
```
This creates a single commit on top of the master branch with a concatenation of all the commit messages that are squashed.

**Comment by jianyangli** [comment]
Thanks @migueldvb !  I got the squash merge work.  @mommermi do you want me to replace this PR with the squash-merged one?

**Comment by jianyangli** [comment]
Closed in favor of #134

**Pull request closed without merging**
