### PR TITLE
Allow unit check for decorator quantity_to_dataclass

### PR DESCRIPTION
**Pull request by jianyangli**
This PR adds an option for `quantity_to_dataclass` decorator to check the unit of input quantity, similar to what `astropy.units.quantity_input` does:

```
import astropy.units as u
import sbpy.data as sbd
@sbd.quantity_to_dataclass(eph=(sbd.Ephem, 'rh', 'length'))
def temperature(eph):
    return 278 * u.K / (eph['rh'] / u.au)**0.5
print(temperature(1 * u.s))
```

Raise exception:

```
UnitsError: Argument 'eph' to function 'temperature' must be in units convertible to 'm'.
```

This is needed in order to enforce quantity input for our functions.  I tried to stack the `astropy.units.quantity_input` decorator with our `quantity_to_dataclass` decorator but it doesn't work when the input is already a `DataClass` object.

This implementation uses some internal functions of `astropy.units.decorators`.  If no objections, I'll merge it in a day.

### CODE REVIEW

**Comment by mommermi** [comment]
@jianyangli This looks good to me! It is not clear to me how you check the dimension against `Quantity`, but I was wondering if we could use the information from [here](https://github.com/NASA-Planetary-Science/sbpy/blob/788d5e1b5392a92943cb17ae7feb755ab51c49e8/sbpy/data/__init__.py#L14) instead of having to provide our own dimensions in the decorator?

**Comment by jianyangli** [comment]
@mommermi Good point!  Also this can be used to check whether the specified field is legal in `sbpy`.  I'll do it tomorrow (already past midnight in China now).

**Comment by mommermi** [comment]
Thanks! If we need to change labels in the field name list, we can do that easily. Also, if we have to delay release that's fine, too.

**Comment by mkelley** [comment]
Instead, I recommend considering replacing the 'length', 'angular velocity', etc. descriptions with base units (meters, radian per second, etc) that can be directly tested via `unit.is_equivalent`.

I also recommending the testing take place in DataClass, rather than the decorator.  Then all input units can be checked.  This can be a v0.5 milestone.

**Comment by jianyangli** [comment]
@mkelley I totally agree.  We should standardize the dimension column in a way that simplifies the processing in code.  For example, 'length' can be recognized by `astropy.units` as a valid physical type of units, but `velocity` cannot.  For this reason, I had many lines in `quantity_to_dataclass` to process the strings that are not recognizable by `astropy.units`.

And I also agree that we do the test in DataClass, so the test will include all the lines in the field name list table.  v0.5 sounds like a good milestone to do all of these.

I'll file an issue to document these suggestions.

**Comment by jianyangli** [comment]
Issue #221

**Pull request merged**
