### PR TITLE
Monkeypatching pyradex functionality for testing

### PR DESCRIPTION
**Pull request by migueldvb**
Mocking `NonLTE.from_pyradex` to try to improve the code coverage.

### CODE REVIEW

**Comment by mommermi** [comment]
@migueldvb I fixed the test, but I find it weird that `nonLTE.from_pyradex` would return a set instead of a `Quantity`. Is that a consequence of your monkeypatching?

**Comment by migueldvb** [comment]
`nonLTE.from_pyradex` returns an Quantity (column density) but the mocked version is just a dictionary with a value to make it simple. Let me make it return a Quantity as well.

**Comment by mommermi** [comment]
Perfect, thanks! Is this ready for merging?

**Comment by migueldvb** [comment]
Yes, it should be ready now.

**Pull request merged**
