### PR TITLE
EXP: Add tomli to doc build req

### PR DESCRIPTION
**Pull request by pllim**
Just trying to narrow down what broke the docs as reported in https://github.com/astropy/sphinx-astropy/issues/61

😬

### CODE REVIEW

**Comment by pllim** [comment]
@mkelley , can you pls approve the Actions? 🙏

**Review by mkelley — APPROVED** [review]

**Comment by pllim** [comment]
Ugh nvm... I think I found the reason and the fix is indeed upstream in sphinx-astropy. For whatever reason, `pip` was choking on the requirement name "v2". Maybe it is some obscure bug they finally fixed in Python 3.11. I will have to make another release upstream.

**Comment by mkelley** [comment]
Got it, thanks for looking into it!

**Comment by pllim** [comment]
Thanks for reporting this! It was an oversight on my part.

**Pull request closed without merging**
