### PR TITLE
bugfix in `sbpy.photometry`

### PR DESCRIPTION
**Pull request by jianyangli**
Replace PR #283

Fix different results between model evaluation and direct call to .evaluate method for photometry models

### CODE REVIEW

**Comment by jianyangli** [comment]
@mkelley Looks like the test failure is related to pyoorb?

**Comment by mkelley** [comment]
@jianyangli Indeed.  I just needed to link the gfortran command to one of the installed versions.  Seems to be fixed now and I've restarted the tests.

**Comment by mkelley** [comment]
@jianyangli , I think you need to rebase to get the new github actions workflow settings.

**Comment by jianyangli** [comment]
Closed and replace by #288

**Pull request closed without merging**
