### PR TITLE
Fix for Issue #100: from_horizons now supports multiple Time values

### PR DESCRIPTION
**Pull request by gianninapr**
This fixes issue #100 to support all instances that are allowed according to the documentation: None, Time object, Time object which date values are a list of dates, dictionaries, plain list of julian dates, and a list of separately created Time objects. If we prefer shorter implementation code we could tweak the documentation to only allow None, dictionaries, or Time objects with either 1 date or a list of dates as such:

`epochs = Time('2015-01-01')`

or

`epochs = Time(['2015-01-01', '2015-01-02'])`

Let me know if there's any advice for anything to add or if we want to limit the user options for the input in order to make the code more concise.

### CODE REVIEW

**Comment by mkelley** [comment]
I think the master branch is back into shape.  @gianninapr , can you rebase?

I like limiting inputs to None, dictionaries, or Time.  What does @mommermi think?

**Comment by mommermi** [comment]
Hmm. Forcing users to provide `... epoch={'jd':2154200}, ...`? At first I thought that would be a bad idea, but in the end, it's not that much more typing. And it might help educate users to actually prefer using `Time` objects... Let's discuss this on slack...

**Comment by mommermi** [comment]
@gianninapr  this is ready to be merged, right?

**Comment by gianninapr** [comment]
> @gianninapr this is ready to be merged, right?

Yes

**Comment by mommermi** [comment]
Perfect, thanks, Giannina!

**Pull request merged**
