### PR TITLE
Better handling of optional packages in ginga_plugins.

### PR DESCRIPTION
**Pull request by mkelley**
Optional packages are:
* ginga
* photutils

### CODE REVIEW

**Comment by mkelley** [comment]
Looks like this is working, @gianninapr .  @mommermi or @migueldvb , should this be all I need to do?

**Comment by mkelley** [comment]
Let me add some notes in the documentation.

**Comment by gianninapr** [comment]
@mkelley I'll see if the build of PR #92 runs without ginga as a requirement, if it does then that should be good, at least from my part

**Comment by mkelley** [comment]
I put a space in the main documentation page for lists of required and optional packages.  I know this is incomplete, and I'm sure that it is evolving.  Unless something is totally wrong in this PR, I recommend address fixes in another issue / PR.

**Comment by mommermi** [comment]
looks good to me, thanks for taking care of this!

**Pull request merged**
