### PR TITLE
Infrastructure migration

### PR DESCRIPTION
**Pull request by migueldvb**
This pull request will move from astropy-helpers to more standard Python packaging tools following the migration guide. The motivation for this change are discussed in [Astropy Proposal for Enhancements: APE 17: A roadmap for package infrastructure without astropy-helpers](https://github.com/astropy/astropy-APEs/blob/master/APE17.rst).

### CODE REVIEW

**Comment by jianyangli** [comment]
Is this PR partially overlapped or completely overridden by the recent PR #284 by @mkelley, and can therefore be closed without merge?

**Comment by mkelley** [comment]
Sorry, @migueldvb , I should have worked off of this PR.  I don't have coverage reporting working yet, it looks like the documentation configuration could also be merged, and setup.cfg should get compared in detail, so there is still some use for this PR.

**Comment by migueldvb** [comment]
OK! I think that this was working using Travis CI but there are conflicts currently. I can fix the conflicts and rebase if this is useful.

**Comment by mkelley** [comment]
@migueldvb  I don't think we want Travis any more, so I've moved the CI tests to GitHub actions.  I'll leave it up to you if you want to rebase or just close an open a new PR or whatever.

**Comment by mkelley** [comment]
Coverage reporting is nominally working elsewhere, so I'll close this.

**Pull request closed without merging**
