### PR TITLE
Follow the general guidelines in spectroscopy

### PR DESCRIPTION
**Pull request by migueldvb**
Update spectroscopy function and methods to follow the general guidelines about input and output parameters. @gianninapr could you see if I have missed something? Feel free to make commits to this pull request branch.

### CODE REVIEW

**Comment by gianninapr** [comment]
It looks good, I have my part of it done as well too, is there a way I can commit the changes I have to this PR directly?

**Comment by gianninapr** [comment]
Or should I open my own PR with my own changes? Because all of my changes are in my own repo and I don't know how to apply them to a forked branch from this PR

**Comment by gianninapr** [comment]
I opened my own PR #141 with my changes for now, in any case if we don't find a better way I can always wait for this PR to be merged and then rebase and update my own PR.

**Comment by migueldvb** [comment]
I think that you have access to my sbpy fork, so you could push to the `spec_v0.1` branch with these commands.

```
git remote add miguel https://github.com/migueldvb/sbpy.git
git push miguel spec_v0.1
```

It is OK to merge your changes independently also.

**Comment by gianninapr** [comment]
Okay I can try that.

**Comment by gianninapr** [comment]
It didn't let me push to your branch directly, I'm unsure why. I'll just keep PR #141 open for now

**Comment by migueldvb** [comment]
Maybe the changes need to be rebased on top of the `spec_v0.1` branch to integrate commits from one branch into the other before updating the remote branch? If is completely fine to have another PR if it makes things easier.

**Comment by mommermi** [comment]
Thanks @migueldvb!

**Pull request merged**
