### PR TITLE
Revised photometric calibration system

### PR DESCRIPTION
**Pull request by mkelley**
This PR replaces #172 .

Changes:

1. `Sun`, `Vega`, `SpectralStandard` moved to new `calib` sub-module.
1. Revised photometric calibration system though `ScienceState`
    1. `default_sun` and `default_vega` renamed `solar_spectrum` and `vega_spectrum`.
    1. New `solar_fluxd` and `vega_fluxd`, which calibrate observations through named filters (i.e., strings) without using `synphot`.
1. Duplicated code in `Sun` and `Vega` has been merged into `SpectralStandard`, and support for flux density science states has been added.
1. `SpectralSource.observe()` revised to allow interpolation (as opposed to binning) for wavelengths/frequencies.  Guidance on when to use this option added to the documentation.
1. `SpectralSource.filt()` renamed `SpectralSource.observe_bandpass()` and support for automatically downloading filter bandpasses through `synphot` via strings dropped.  Instead, use `synphot.SpectralElement.from_filter()`.
1. Revised `units`:
    1. Major re-write of equivalencies `spectral_density_vega()` and `reflectance()`.
    1. `reflectance()` now requires bandpass.
1. Revised `activity.dust.Afrho`: passing solar flux density no longer supported.  Instead, use the `ScienceState` `solar_fluxd`.
1. Revised documentation, doctests, and tests.
1. Added Cousins R filter to `photometry/data` and `utils.get_bandpass()`.

### CODE REVIEW

**Comment by mkelley** [comment]
Any questions or comments before merging (assuming checks pass)?

**Comment by mommermi** [comment]
@mkelley: feel free to skip tests resulting in things like this:

> Expected:
>     [5495. 5505. 5515. 5525. 5535.] Angstrom
> Got:
>     [ 5495.  5505.  5515.  5525.  5535.] Angstrom

We can test for one element in this list in the unit tests, so we can skip it in the docs. I think this is caused by different versions of `numpy` behaving differently. I've spend already too much time trying to fix this stuff...

**Comment by mkelley** [comment]
Let me see if +FLOAT_CMP works first.

**Comment by mkelley** [comment]
That doctest flag seems to have taken care of the problem.

**Comment by mkelley** [comment]
Skipping the online solar spectra tests until we can get our own data host (#188).

**Pull request merged**
