### PR TITLE
Fix missing designation for asteroid-named comets.

### PR DESCRIPTION
**Pull request by mkelley**
`Names.parse_comet('P/2010 WK')` returns `{name': 'LINEAR', 'type': 'P'}`

Expected behavior: `{'desig': '2010 WK', 'name': 'LINEAR', 'type': 'P'}`

Fix: Make trailing numbers optional.

### CODE REVIEW

**Comment by mkelley** [comment]
After this fix, I seem to be able to parse all comet names in https://minorplanetcenter.net/iau/lists/LastCometObs.html

**Comment by mommermi** [comment]
Interesting. The build fail is unrelated - why didn't it show up before?

**Comment by mkelley** [comment]
Ah, synphot 0.1.3 was released 4 days ago.

**Comment by mkelley** [comment]
Fix for the test in #131

**Pull request merged**
