### PR TITLE
WIP: add conda recipe

### PR DESCRIPTION
**Pull request by mjuric**
***WORK IN PROGRESS, DO NOT MERGE***

This is a PR to add a conda recipe so sbpy can be cleanly added to conda environments.

TODO
* Still work in progress, because I need to understand how to call the unit tests (i.e., just simply with pytest, w/o pulling in various CI-service helpers). @mommermi @mkelley @migueldvb -- any hints? How do you run pytest when coding/building on your local machines?
* Bump astroquery version to 0.4.1dev0 once it's released to conda-forge (I pinged @bsipocz about this).

### CODE REVIEW

**Comment by bsipocz** [comment]
Shouldn't the recipe go to conda-forge instead?

**Comment by bsipocz** [comment]
This uses the astropy testrunner, ``python setup.py test`` should then pick up all tests. For the installed version there should be a ``sbpy.test()`` from inside a python session.  (Calling pytest directly might work, too). 

There are expected complications due to astropy-helpers, so ping me if the recipe runs into weird setup issues.

**Comment by mkelley** [comment]
I think all three methods appropriately test the module.  For the doctests, I think I've only used setup.py.

**Comment by mkelley** [comment]
Tagging Issue #250

**Comment by mjuric** [comment]
Thanks all!

`python setup.py test` worked, but running just `pytest` made it unhappy:

```
============================================================================= 491 passed, 89 skipped in 29.67s ==============================================================================
(sbpy-dev) [mjuric@caladan (master) ~/projects/github.com/mjuric/sbpy]$ pytest
==================================================================================== test session starts ====================================================================================
platform darwin -- Python 3.8.3, pytest-5.4.3, py-1.8.2, pluggy-0.13.1
rootdir: /Users/mjuric/projects/github.com/mjuric/sbpy, inifile: setup.cfg
plugins: hypothesis-5.16.1, doctestplus-0.7.0, remotedata-0.3.2, arraydiff-0.2, openfiles-0.5.0, astropy-header-0.1.2
collecting ... WARNING: AstropyDeprecationWarning: The astropy.tests.plugins.display plugin has been deprecated. See the pytest-astropy-header documentation for information on migrating to using pytest-astropy-header to customize the pytest header. [astropy.tests.plugins.display]
collected 597 items / 1 error / 596 selected

========================================================================================== ERRORS ===========================================================================================
_____________________________________________________________________ ERROR collecting astropy_helpers/ah_bootstrap.py ______________________________________________________________________
../../../../miniconda3/envs/sbpy-dev/lib/python3.8/site-packages/pytest_doctestplus/plugin.py:175: in collect
    module = self.fspath.pyimport()
../../../../miniconda3/envs/sbpy-dev/lib/python3.8/site-packages/py/_path/local.py:724: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('ah_bootstrap', '/Users/mjuric/projects/github.com/mjuric/sbpy/ah_bootstrap.py', local('/Users/mjuric/projects/github.com/mjuric/sbpy/astropy_helpers/ah_bootstrap.py'))
================================================================================== short test summary info ==================================================================================
ERROR astropy_helpers/ah_bootstrap.py - py._path.local.LocalPath.ImportMismatchError: ('ah_bootstrap', '/Users/mjuric/projects/github.com/mjuric/sbpy/ah_bootstrap.py', local('/Users/mjur...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
===================================================================================== 1 error in 3.58s ======================================================================================
Traceback (most recent call last):
  File "/Users/mjuric/miniconda3/envs/sbpy-dev/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/Users/mjuric/miniconda3/envs/sbpy-dev/lib/python3.8/site-packages/_pytest/config/__init__.py", line 124, in main
    ret = config.hook.pytest_cmdline_main(
  File "/Users/mjuric/miniconda3/envs/sbpy-dev/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/mjuric/miniconda3/envs/sbpy-dev/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/mjuric/miniconda3/envs/sbpy-dev/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/mjuric/miniconda3/envs/sbpy-dev/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/mjuric/miniconda3/envs/sbpy-dev/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/mjuric/miniconda3/envs/sbpy-dev/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/mjuric/miniconda3/envs/sbpy-dev/lib/python3.8/site-packages/_pytest/main.py", line 240, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/Users/mjuric/miniconda3/envs/sbpy-dev/lib/python3.8/site-packages/_pytest/main.py", line 235, in wrap_session
    config._ensure_unconfigure()
  File "/Users/mjuric/miniconda3/envs/sbpy-dev/lib/python3.8/site-packages/_pytest/config/__init__.py", line 825, in _ensure_unconfigure
    self.hook.pytest_unconfigure(config=self)
  File "/Users/mjuric/miniconda3/envs/sbpy-dev/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/mjuric/miniconda3/envs/sbpy-dev/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/mjuric/miniconda3/envs/sbpy-dev/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/mjuric/miniconda3/envs/sbpy-dev/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/mjuric/miniconda3/envs/sbpy-dev/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/mjuric/miniconda3/envs/sbpy-dev/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/mjuric/projects/github.com/mjuric/sbpy/astropy_helpers/astropy_helpers/conftest.py", line 57, in pytest_unconfigure
    combined_cdata.write_file('.coverage.subprocess')
AttributeError: 'CoverageData' object has no attribute 'write_file'
```

**Comment by bsipocz** [comment]
Yes, you should not run pytest on the helpers, but only on `sbpy` and the docs. But then, running pytest is not the recommended way with this infrastructure anyway, and fixing it won't happen as with [APE-17](https://github.com/astropy/astropy-APEs/blob/master/APE17.rst) we decided to deprecate the helpers and provide a migration guide for modern packaging tools (astropy helpers was filling a void when it was created many years ago, but the standard python packaging tools improved a lot since, and basically there isn't much reason to keep it around. We will still do occasional bugfixes to it in the next ~2 years, but won't spend development hours on it).

**Comment by mkelley** [comment]
FYI, we're migrated to the new package setup via #252 .

**Comment by mkelley** [comment]
@mjuric sbpy is conda installable via conda-forge, thanks to @mwcraig 🎉 !  https://anaconda.org/conda-forge/sbpy

**Pull request closed without merging**
