### PR TITLE
Provide correct slope for color ratios with `SpectralGradient.from_color`

### PR DESCRIPTION
**Pull request by mkelley**
Addresses #389

### CODE REVIEW

**Comment by hhsieh00** [comment]
Sorry, just getting to this now.  In the code diff view, Codecov indicates that there are several new lines not covered by tests.  Is this a problem (I note that the Codecov summary report on this page says that all "coverable" lines are covered)?  Otherwise, the changes look good to me.

**Comment by mkelley** [comment]
Those reported lines don't make sense.  They show up as covered in the codecov app: https://app.codecov.io/gh/NASA-Planetary-Science/sbpy/pull/392/blob/sbpy/spectroscopy/core.py

**Comment by mkelley** [comment]
I've rebased.  Maybe that will fix them?  If not, I think the coverage report should take precedence.

**Review by hhsieh00 — APPROVED** [review]
Okay, that sounds fine to me.  Yeah, the contradiction between the different reports is a bit strange (I still see the comments in the code diffs).

**Comment by mkelley** [comment]
I can refresh the codecov check and it'll report 100% covered as it should.  But the diff report always lists those lines as uncovered.  Anyway, something to keep in mind in other reviews.

**Pull request merged**
