### PR TITLE
Add support for astropy stable

### PR DESCRIPTION
**Pull request by migueldvb**
`InheritDocstrings` metaclass has been dropped in astropy 4.0 so we don't need to have it in the metaclass definition for astropy>=4.

### CODE REVIEW

**Comment by migueldvb** [comment]
This part was working locally for astropy 3 and 4, but I didn't notice
that synphot 1.3 is not supported with astropy 4.0. It seems that we
also need to change a doctest in `spectroscopy/sources.rst` (should
work now for synphot >= 2). I have changed the required versions in
the travis configuration and restarted the checks.

**Comment by migueldvb** [comment]
codecov is working fine but the Horizons remote tests are still failing.

**Comment by migueldvb** [comment]
This is ready to be looked at, but no rush.

**Comment by mkelley** [comment]
Looks good, thanks!

**Pull request merged**
