### PR TITLE
Move utils.get_bandpass to photometry.bandpass.

### PR DESCRIPTION
**Pull request by mkelley**
@mommermi @jianyangli @migueldvb  Any requests for filters to add?  Currently:
```
    +-------------+---------------------------+
    | Name        | Source                    |
    +=============+===========================+
    | WFC3 F438W  | HST/WFC3 UVIS, v4         |
    +-------------+---------------------------+
    | WFC3 F606W  | HST/WFC3 UVIS, v4         |
    +-------------+---------------------------+
    | Johnson V   | STScI CDBS, v4            |
    +-------------+---------------------------+
    | Cousins R   | STScI CDBS, v4            |
    +-------------+---------------------------+
    | Cousins I   | STScI CDBS, v4            |
    +-------------+---------------------------+
    | SDSS u      | SDSS, dated 2001          |
    +-------------+---------------------------+
    | SDSS g      | SDSS, dated 2001          |
    +-------------+---------------------------+
    | SDSS r      | SDSS, dated 2001          |
    +-------------+---------------------------+
    | SDSS i      | SDSS, dated 2001          |
    +-------------+---------------------------+
    | SDSS z      | SDSS, dated 2001          |
    +-------------+---------------------------+
```

### CODE REVIEW

**Comment by mommermi** [comment]
How about:
* Johnson B
* JHK

?

**Comment by migueldvb** [comment]
Maybe also `y` band ( LSST bandpass transmission is defined here https://github.com/lsst/throughputs/tree/master/baseline or Pan-STARRS )

**Comment by jianyangli** [comment]
@mkelley Are you sure you want to make this a general use utility for users?  There are just too many filters out there.  You will constantly get requests and complaints about filters not included.  Where do you draw the line?

**Comment by mkelley** [comment]
Right, so whatever we define here is final.  I'll add to the documentation how to create your own.  I'd like to have an automatic way to incorporate the all filters at STScI, but that is a bigger project, so I will have to table it for now.

**Comment by mkelley** [comment]
Added PanSTARRS1, 2MASS, WISE, Johnson U and B.  They add up to 0.5 MB of data.

**Pull request merged**
