### PR TITLE
Ceres's targetname changed at JPL SBDB.

### PR DESCRIPTION
**Pull request by mkelley**
Update tests to reflect the change.

### CODE REVIEW

**Comment by migueldvb** [comment]
good catch!

**Comment by migueldvb** [comment]
From the  travis log a change in `docs/sbpy/photometry.rst` is needed (line 87).
```
  INFO: Model initialized for 1 Ceres. [sbpy.photometry.core]
```
to:
```
  INFO: Model initialized for 1 Ceres (A801 AA).  [sbpy.photometry.core]
```

**Comment by mkelley** [comment]
MPC ephemeris service erroring again.  I've emailed them about it.

**Comment by migueldvb** [comment]
MPC service is working again and this PR looks ready to merge. I have contacted codecov support about the 400 errors. I will try to update the codecov uploader to fix the problem.

> 
> ​Codecov recently did some fundamental storage changes on its backend in an effort to greatly improve the reliability of our underlying storage systems. As a result the X-Amz-Acl: public-read header is no longer needed, and may result in 400 errors if used.
> 
> It looks like you are using the python uploader. Can you please update to the latest version and try again please?

**Pull request merged**
