### PR TITLE
Updating astropy_helpers to 2.0.8

### PR DESCRIPTION
**Pull request by migueldvb**
This merges the latest astropy-helpers 2.0.8. Hopefully all the checks will pass.

### CODE REVIEW

**Comment by mkelley** [comment]
Since we're no longer supporting python2, should this be a 3.x branch of AH?

**Comment by mkelley** [comment]
Ah, or do we need to match the earliest astropy that we support, which I think is still 2.x.

**Comment by migueldvb** [comment]
I think that is true. We could stay with astropy-helpers 2.0.8 for the time being.

**Comment by mkelley** [comment]
Sounds good.

**Pull request merged**
