### PR TITLE
Add CALSPEC model solar spectrum

### PR DESCRIPTION
**Pull request by mkelley**
Adding support for a R=5000 model solar spectrum from STScI's CALSPEC database.

### CODE REVIEW

**Comment by mkelley** [comment]
Requires #370 .

**Comment by jianyangli** [comment]
I see some conflicts/duplicates in this PR with #370 .  I assume this PR will be rebased and duplicates resolved before we should review and merge?

**Comment by mkelley** [comment]
The decrease in coverage is due to adding a remote test.  So, this is ready for review.

**Review by jianyangli — APPROVED** [review]
Just curious: In your recent few PRs, you are changing single quote (') to double quote (").  Is that something new in Python 3.10 or 3.11?  I'm still using 3.8, but wondering whether I need to do the same to my personal code if I upgrade.  Thanks.

**Comment by mkelley** [comment]
It isn't important, just a style preference.  I like to use the Black
formatter and it automatically does the change "The main reason to
standardize on a single form of quotes is aesthetics. Having one kind of
quotes everywhere reduces reader distraction."
https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#strings

**Pull request merged**
